# Generated by Django 2.0.3 on 2022-09-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('sconto', models.IntegerField()),
                ('prezzo', models.FloatField()),
                ('prezzo_finale', models.FloatField()),
                ('prezzo_buy', models.FloatField()),
            ],
        ),
    ]
