# Generated by Django 2.1.5 on 2022-09-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_catalogo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
