# Generated by Django 2.1.5 on 2022-09-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220914_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecensionePostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
                ('contenuto', models.TextField()),
            ],
        ),
    ]
