# Generated by Django 2.1.5 on 2022-09-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220921_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='new_product',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
