# Generated by Django 2.1.5 on 2022-09-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_vasifiltrimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='numero_bacelli',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
