# Generated by Django 2.1.5 on 2022-10-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_recensionepostmodel_valutazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensionepostmodel',
            name='titolo',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
