# Generated by Django 2.1.5 on 2022-10-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_catalogo_media_voto_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='media_voto_decimal',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
