# Generated by Django 2.1.5 on 2022-10-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_catalogo_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='numero_recensioni',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
