# Generated by Django 2.1.5 on 2022-10-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_catalogo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='user',
        ),
    ]
