# Generated by Django 2.1.5 on 2022-10-17 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_recensionepostmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recensionepostmodel',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='recensionepostmodel',
            name='nome',
        ),
        migrations.AddField(
            model_name='recensionepostmodel',
            name='data',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
