# Generated by Django 2.1.5 on 2022-10-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_recensionepostmodel_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensionepostmodel',
            name='immagine',
            field=models.ImageField(upload_to=''),
        ),
    ]
