# Generated by Django 2.1.5 on 2022-10-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20221017_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensionepostmodel',
            name='immagine_1',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
