# Generated by Django 2.1.5 on 2022-09-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagamenti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendite',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Catalogo'),
        ),
    ]
