# Generated by Django 2.1.5 on 2022-09-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_recensionepostmodel_prodotto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensionepostmodel',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Catalogo'),
        ),
    ]
