# Generated by Django 2.1.5 on 2022-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_catalogo_new_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='risparmia',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
