# Generated by Django 2.1.5 on 2022-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_catalogo_risparmia'),
    ]

    operations = [
        migrations.CreateModel(
            name='VasiFiltriModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sei_bacelli', models.BooleanField()),
                ('dodici_bacelli', models.BooleanField()),
                ('otto_bacelli', models.BooleanField()),
            ],
        ),
    ]
