# Generated by Django 2.1.5 on 2022-10-05 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_catalogo_numero_bacelli'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensionepostmodel',
            name='valutazione',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
