# Generated by Django 2.1.5 on 2022-10-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_catalogo_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='roi',
            field=models.FloatField(default=3.5),
            preserve_default=False,
        ),
    ]
