# Generated by Django 2.1.5 on 2022-10-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_catalogo_roi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='roi',
        ),
    ]
