# Generated by Django 2.1.5 on 2022-10-16 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('store', '0022_user'),
    ]

    operations = [
       
       
        migrations.AddField(
            model_name='catalogo',
            name='user',
            field=models.ForeignKey(default='Pangea', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
