# Generated by Django 2.1.5 on 2022-10-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20221017_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='user',
        ),
    ]
