# Generated by Django 2.1.5 on 2022-10-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20221017_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensionepostmodel',
            name='immagini',
            field=models.ImageField(default='PangeaProject/static/baobab.png', upload_to=''),
        ),
    ]
