# Generated by Django 2.1.5 on 2022-10-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_recensionepostmodel_immagini'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensionepostmodel',
            name='immagine',
            field=models.ImageField(default='baobab.png', upload_to=''),
            preserve_default=False,
        ),
    ]
