# Generated by Django 2.1.5 on 2022-10-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_recensionepostmodel_immagine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recensionepostmodel',
            name='immagine',
        ),
    ]
