# Generated by Django 2.1.5 on 2022-10-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_recensionepostmodel_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensionepostmodel',
            name='image',
            field=models.ImageField(default='/static/tiktik.png', upload_to=''),
        ),
    ]
