# Generated by Django 2.1.5 on 2022-10-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_recensionepostmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensionepostmodel',
            name='nome',
            field=models.CharField(default='pangea', max_length=20),
            preserve_default=False,
        ),
    ]
