# Generated by Django 2.1.5 on 2022-10-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_recensionepostmodel_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensionepostmodel',
            name='immagine',
            field=models.ImageField(default='/static/baobab.png', upload_to=''),
        ),
    ]
