# Generated by Django 2.1.5 on 2022-10-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20221017_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recensionepostmodel',
            name='immagine',
        ),
        migrations.AddField(
            model_name='recensionepostmodel',
            name='immagine_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recensionepostmodel',
            name='immagine_2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recensionepostmodel',
            name='immagine_3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
