# Generated by Django 2.1.5 on 2022-10-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20221017_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensionepostmodel',
            name='immagine_1',
            field=models.ImageField(blank=True, upload_to='static/revisioni'),
        ),
    ]
