# Generated by Django 2.1.5 on 2022-10-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_auto_20221017_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='catalogo',
            name='stripe_product_id',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recensionepostmodel',
            name='immagine_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/revisioni'),
        ),
        migrations.AlterField(
            model_name='recensionepostmodel',
            name='immagine_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/revisioni'),
        ),
        migrations.AlterField(
            model_name='recensionepostmodel',
            name='immagine_3',
            field=models.ImageField(blank=True, null=True, upload_to='static/revisioni'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Catalogo'),
        ),
    ]
