# Generated by Django 2.1.5 on 2023-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_catalogo_descrizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colore', models.CharField(max_length=15)),
                ('codice', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='catalogo',
            name='spedizione',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='prodotto',
            field=models.ManyToManyField(to='store.Catalogo'),
        ),
    ]
